package-lock.json
package.json

promote dev to master

---

README.md
commands/metamask.js
commands/puppeteer.js
helpers.js
pages/metamask/main-page.js
plugins/index.js
support/commands.js
support/index.d.ts

Adds support for custom networks in synpress.

feat: add custom network support

---

commands/metamask.js
pages/metamask/notification-page.js
plugins/index.js
support/commands.js
support/index.d.ts

There is a metamask screen where user has to approve permission on a site.
So, I added a cypress task for it.
Can you please take a look and how soon it can be released?

feat: add approve permissions

---

pages/metamask/notification-page.js

fix: metamask notification buttons misspell

---

.github/workflows/release.yml

ci: release beta versions automatically

---

commands/metamask.js
pages/metamask/notification-page.js
plugins/index.js
support/commands.js
support/index.d.ts

Hi Synthetix friends! 
Thank you for this lovely library. It has greatly helped the testing efforts for our project.
We needed to sign/reject signatures in metamask, so I implemented those commands in a fork.
Is this something that would be useful to merge into the main repo? 
Thank you again!

Adding metamask signature commands.

---

README.md
support/commands.js

fixed SKIP_RESOURCES_WAIT functionality

---

package-lock.json
package.json

fix: node-fetch incompatibility

---

commands/metamask.js
pages/metamask/notification-page.js
plugins/index.js
support/commands.js
support/index.d.ts

Seems that nobody has created a PR for this, so I try to contribute this...
Usage: `cy.acceptMetamaskAccess(true);`

Allow to select all accounts when accepting dApp connection

---

commands/metamask.js
plugins/index.js
support/commands.js

fix: linting issues

---

package-lock.json
package.json

Signed-off-by: Jakub <ci@drptbl.dev>

keep dev up to date

---

commands/metamask.js

fix: close disconnect popup on disconnectWalletFromAllDapps

---

.eslintrc.js
README.md
helpers.js
launcher.js
package.json
synpress.config.js
synpress.js

Basic logging for a good start.

feat: add logging and missing cli features

---

commands/metamask.js

fix: importAccount goto triggered too fast

---

.github/workflows/audit_and_lint.yml
commands/metamask.js
docker-compose.ci.yml
docker-compose.yml
package.json
tests/e2e/specs/metamask-spec.js

blocked by:
update metamask to v10+ (https://github.com/Synthetixio/synpress/issues/255)
(contract creation fails pre-eip1559)
will be merged after above is done.

feat: use anvil for e2e testing

---

.github/workflows/audit_and_lint.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
helpers.js
package.json
yarn.lock

Hi,
1) Updated few deps in synpress
2) Updated deps in yarn.lock file to fix vulnerabilities
3) Fixed an issue with ethers (introduced after some previous deps update)
4) Updated some deps in ci
Thx, cheerZ.

Update deps (yarn+ci) & fix ethers

---

commands/playwright.js

Due to a recently merged PR #650, all tests were broken.

Fix broken tests

---

package.json
yarn.lock

fix issue with testing-library/dom on CI with typescript
https://github.com/Synthetixio/synpress/actions/runs/4377699975/jobs/7661506342
N/A

🚑 testing-library/dom typescript issue

---

commands/metamask.js
commands/playwright.js
pages/metamask/first-time-flow-page.js
pages/metamask/page.js

if critical error happens reload the page
no
N/A

Handle crit error

---

commands/metamask.js
docs/synpress-commands.md
pages/metamask/settings-page.js
plugins/index.js
support/commands.js
support/index.d.ts

fix issue with experimental and advanced settings and token allowance
add activateEthSignRequestsInMetamask
#675
N/A

Fix adv/exp settings

---

support/index.js

Duplicate of #894 but with working CI.
Kudos to @YakovL! 🔥

Remove Promise wrap from `cy.setupMetamask()`

---

.gitignore
docs/package.json
examples/new-dawn/package.json
package.json
packages/core/package.json
packages/fixtures/package.json
pnpm-lock.yaml
release/package.json
wallets/metamask/package.json

Clearly and concisely describe the feature added/isses being solved.
#(issue)
N/A

📌 chore: Lock and update deps

---

turbo.json

Clearly and concisely describe the feature added/isses being solved.
https://linear.app/synpress/issue/SYN-55/vercel-build-is-failing
N/A

🐛 fix: Update output path for docs:build task

---

wallets/metamask/src/metamask.ts
wallets/metamask/test/e2e/metamask/approvePermission.spec.ts
wallets/metamask/test/e2e/metamask/connectToDapp.spec.ts

Missing end to end tests for permissions.

:technologist: feat: Missing permissions tests
