support/commands.js, support/index.d.ts
added:
- getId
- getText
- waitUntilExist
=> feat: add new custom commands

README.md, commands/metamask.js, pages/metamask/first-time-flow-page.js, pages/metamask/main-page.js, plugins/index.js
Thanks for building this! I was looking to set up e2e tests locally that would interact with a node provisioned by hardhat, but realized I'd need to pass in a private key, rather than a mnemonic phrase, to connect a wallet. This PR adds support for this. The browser automation looks like [this](https://www.loom.com/share/fead844cb0a548bab94dbb11b30d204e).
If you're interested in merging, happy to make further updates. Let me know.
=> Adds support for importing wallets using private keys

commands/metamask.js
It's very possible that the gas limit doesn't update in 3 seconds, and then the transaction fails.
Checking the field of gas limit would prevent this from happening.
=> Fix confirm transaction may not work

commands/metamask.js, plugins/index.js, support/commands.js, support/index.d.ts
Sometimes the `cy.confirmMetamaskTransaction` timeouts for my tests. After some investigation, I found that it's because the MetaMask can't get the gas limit or take too much time to get it. So I added a `gasConfig` parameter to `confirmMetamaskTransaction()` and I don't need to wait for the gas limit response from MetaMask anymore. :)
=> Add configs for gas fee and gas limit

commands/metamask.js
When Metamask popup still open, some methods can fail. 
[`importWallet`](https://github.com/Synthetixio/synpress/blob/dev/commands/metamask.js#L84-L90) and [`createWallet`](https://github.com/Synthetixio/synpress/blob/dev/commands/metamask.js#L112-L118) methods close popups well, but is missing in [`unlock`](https://github.com/Synthetixio/synpress/blob/b3e6f593063f5819e63b4dfebce8359106f2ed4f/commands/metamask.js#L58-L63).
Create new `closeMetamaskPopup` method and use it in `importWallet`, `createWallet` and `unlock`.
=> fix unlock close popup

helpers.js
This will resolve both `node_modules/@synthetixio/synpress` and the [Yarn PnP](https://yarnpkg.com/features/pnp) equivalent, which is something like `.yarn/cache/@synthetixio-synpress-npm-{version&hash}.zip/node_modules/@synthetixio/synpress `.
=> Add Yarn PnP support

commands/puppeteer.js
when message content is too long, the button is not visible in the current window, add foucs to make sure the button can be clicked.
=> update: make sure button can be clicked

commands/metamask.js
I have noticed that after switching to Playwright there are some problems when adding and switching networks - it occur that after adding network Synpress was waiting until the mm window is closed before switching network
=> Fixed allowMetamaskToAddAndSwitchNetwork

commands/metamask.js
I have noticed a bug from this pr https://github.com/Synthetixio/synpress/commit/65254698e1e2a77fc4d1b03b91fb84f4d3c9b281 that breaks addAndSwitchNetwork 
```
CypressError: `cy.task('allowMetamaskToAddAndSwitchNetwork')` failed with the following error:
> Cannot destructure property 'waitForEvent' of 'undefined' as it is undefined.
https://on.cypress.io/api/task
at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:145679:78)
at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11318:23)
at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9253:31)
at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9310:18)
at Promise._settlePromise0 …
```
=> Default param in allowToAddNetwork to object

support/index.d.ts
I'm using typescript with synpress
my IDE was complaining about the required argument when I called `cy.acceptMetamaskAccess()`
and it only accepted `cy.acceptMetamaskAccess(undefined)`
This change will allow `cy.acceptMetamaskAccess()` to be used in .ts files
=> fix: allow optional params instead of requiring explicit undefined param

support/index.d.ts
Great work with the library :)
While using it, I noticed that the documentation of `addMetamaskNetwork` could've been a little bit clearer - this method not only adds a new network but also switches to it in the process. 
Ideally, this method should also be named just like another method`allowMetamaskToAddAndSwitchNetwork` is named which clearly tells what the function would do.
=> docs: addMetamaskNetwork description made clearer

docs/synpress-commands.md
This PR document the Synpress Commands (API) in a markdown instead of having it only in the `types.d.ts` file
=> docs: document all synpress commands in `docs/synpress-commands.md`

Dockerfile
The [synthetixio/docker-e2e](https://hub.docker.com/r/synthetixio/docker-e2e/tags) only runs on `linux/amd64` machines. 
Which basically will not run directly on `arm64` (M1 / M2 MacBooks). 
As for now the latest version of docker (14.6.2) supports running `linux/amd64` images under **Rosetta 2**
Read this article for more info [Docker on Apple Silicon Mac: How to Run x86 Containers with Rosetta 2](https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5)  
Adding this flag `--platform=linux/amd64` will automatically run the docker image under **Rosetta 2**.
=> chore: add the docker image platform to be linux/amd64

package.json, src/commands/etherscan.ts, src/commands/metamask.ts, src/plugins/index.js, yarn.lock
The main goal of this PR is to migrate `src/commands/metamask.js` and `src/commands/etherscan.js` to use TS instead of JS. This work is a continuation of the TS setup done on #691 .
=> feat: TS migration pt.1 - `metamask.ts` & `etherscan.ts`

Dockerfile, docker-compose.ci.yml, docker-compose.yml, nginx.conf, tests/e2e/specs/metamask-spec.js
Integrating Nginx allows us to redirect `http://127.0.0.1:8545` calls to `http://foundry:8545` and `http://127.0.0.1:8546` calls to `http://foundry-metamask-test-dapp:8546`. With this, we don't have to worry about conditionally handling RPC URLs or RPC calls to a local node from the MetaMask Test Dap when running tests in docker.
=> Unskip MetaMask add/switch network tests

commands/metamask.js
=> Close new network popup after switching networks

.github/workflows/test.yml, wallets/metamask/playwright.config.ts
UX of unzipping the artifact once downloaded is not ideal, but it should be enough for now.
=> 👷 chore(ci): Archive Playwright traces for E2E tests

commands/metamask.js, commands/playwright.js
In localized Chrome version extension would be reported as `Identifier: ID` instead of just an `ID`. This fix handles that behavior
setupMetamask would hang as there will be no `metamaskPage` in commands/playwright
Tested with Chrome 116 and 118 (arm)
=> Fix localized Chrome's extension id

.github/workflows/test.yml
Disabling headless E2E tests for now due to a bug in MetaMask in [this](https://github.com/MetaMask/metamask-extension/blob/f5942b19a3cbac2f3059a81b71390adbbd95a933/app/scripts/lib/notification-manager.js#L38) function. Possibly, this bug is also related to a polyfill they use.
=> 👷 chore(ci): Disable headless tests

docs/api/classes/MetaMask.md, docs/docs/guides/playwright.md, wallets/metamask/src/metamask.ts, wallets/metamask/src/pages/NotificationPage/actions/connectToDapp.ts, wallets/metamask/src/pages/NotificationPage/page.ts, wallets/metamask/src/pages/NotificationPage/selectors/connectPage.ts, wallets/metamask/src/pages/NotificationPage/selectors/index.ts, wallets/metamask/test/e2e/metamask/connectToDapp.spec.ts
As MetaMask supports multiple account connection in a single flow, we should support that journey as well.
https://linear.app/synpress/issue/SYN-38/add-support-for-selecting-multipleall-accounts-in
=> :sparkles: feat: Support multiple accounts connection

packages/core/src/utils/getWalletSetupFuncHash.ts, packages/core/test/defineWalletSetup.test.ts, packages/core/test/utils/getWalletSetupFuncHash.test.ts
=> 🚑️ fix(core): Minify whitespaces when compiling setup files

wallets/metamask/src/metamask.ts, wallets/metamask/src/pages/NotificationPage/actions/signSimpleMessage.ts, wallets/metamask/src/pages/NotificationPage/page.ts, wallets/metamask/src/pages/NotificationPage/selectors/signaturePage.ts, wallets/metamask/src/pages/SettingsPage/actions/disableEthSign.ts, wallets/metamask/src/pages/SettingsPage/actions/enableEthSign.ts, wallets/metamask/src/pages/SettingsPage/actions/index.ts, wallets/metamask/src/pages/SettingsPage/page.ts, wallets/metamask/src/pages/SettingsPage/selectors/index.ts, wallets/metamask/test/e2e/metamask/confirmSignature.spec.ts
Implemented MetaMask settings page instance to be able to change advanced settings. Then added `sign_eth` method.
---
<details open="true"><summary>Generated summary</summary>
> ## TL;DR
> This pull request adds new methods and properties to the MetaMask class, including enabling and disabling the eth_sign feature in advanced settings. It also includes changes to the NotificationPage and SettingsPage classes for interacting with confirmation modals and toggling Ethereum signing.
> 
> ## What changed
> - Added new import for SettingsPage and property settingsPage to MetaMask class
> - Added confirmSignatureWithRisk method to MetaMask class
> - Added enableEthSignUnsafe method to MetaMask class
> - Added …
=> :sparkles: feat: Implemented sign_eth method with MetaMask settings page

wallets/metamask/test/e2e/metamask/addNewToken.spec.ts
Watch token using EIP747
https://linear.app/synpress/issue/SYN-65/watch-token-using-eip747
---
<details open="true"><summary>Generated summary</summary>
> # TL;DR
> This pull request adds a new end-to-end test for adding a new token using EIP747 in the MetaMask wallet.
> 
> # What changed
> A new test case has been added to the `addNewToken.spec.ts` file. This test case simulates the process of adding a new token using EIP747. It fills in the contract address, symbol, and decimals for the new token, clicks the watch button, and then checks that the token has been added successfully.
> 
> # How to test
> To test this change, you can run the end-to-end tests for the MetaMask wallet. The new test case should …
=> :sparkles: feat: Watch token using EIP747

wallets/metamask/test/e2e/metamask/PPOM.spec.ts, wallets/metamask/test/e2e/metamask/confirmTransaction.spec.ts
MetaMask PPOM tested.
https://linear.app/synpress/issue/SYN-66/metamask-ppom-tests
---
<details open="true"><summary>Generated summary</summary>
> ## TL;DR
> This pull request introduces a new set of tests for the MetaMask wallet, specifically focusing on the PPOM security mechanism. It also adds a new test for the custom transaction form.
> 
> ## What changed
> Two files were modified in this pull request:
> 
> 1. `wallets/metamask/test/e2e/metamask/PPOM.spec.ts`: This is a new file that contains tests for the PPOM security mechanism. It checks if the mechanism can prevent malicious ETH transfers, ERC20 transfers, ERC20 approvals, approvals for all, permits, trade orders, and seaports.
> 
> 2. …
=> ✨ feat: MetaMask PPOM tests

examples/new-dawn/test/e2e/00_mock.spec.ts, packages/tsconfig/base.json, pnpm-lock.yaml, release/package.json, release/src/index.ts, wallets/metamask-mock/environment.d.ts, wallets/metamask-mock/package.json, wallets/metamask-mock/playwright.config.ts, wallets/metamask-mock/src/index.ts, wallets/metamask-mock/src/metamask-mock.ts, wallets/metamask-mock/src/network/Network.ts, wallets/metamask-mock/src/testWithMetaMaskMock.ts, wallets/metamask-mock/src/utils/index.ts, wallets/metamask-mock/src/utils/mockEthereum.ts, wallets/metamask-mock/test/e2e/metamask/addNewAccount.spec.ts, wallets/metamask-mock/test/e2e/metamask/importWalletFromPrivateKey.spec.ts, wallets/metamask-mock/test/e2e/metamask/mock/mockEthereum.spec.ts, wallets/metamask-mock/test/e2e/metamask/switchAccount.spec.ts, wallets/metamask-mock/test/e2e/metamask/switchNetwork.spec.ts, wallets/metamask-mock/tsconfig.build.json, wallets/metamask-mock/tsconfig.json, wallets/metamask-mock/tsup.config.ts, wallets/metamask-mock/vitest.config.ts, wallets/metamask/test/e2e/metamask/PPOM.spec.ts, wallets/metamask/test/e2e/metamask/connectToDapp.spec.ts
Synpress with MetaMask mocked wallet.
https://linear.app/synpress/issue/SYN-71/mock-metamask-wallet-api
=> ✨ feat: Synpress with MetaMask mock

wallets/metamask/test/e2e/connectToDapp.spec.ts
Resolves tricky test case for the `connectToDapp` function.
N/A
=> :bug: fix: Resolved connectToDapp test issue

commands/metamask.js, package.json, pages/metamask/first-time-flow-page.js, pages/metamask/main-page.js, pages/metamask/notification-page.js, pages/metamask/settings-page.js, plugins/index.js, pnpm-lock.yaml, tests/e2e/specs/metamask-spec.js
Current version of synpress was missing some commands to setup latest metamask v11.15.5.
In this PR we have fixed First time flow, Main page, Notification and setting page selectors.
#(issue)
N/A
=> fix: fixed metamask commands to support v11.15.5
